# -*- coding: utf-8 -*-
"""Plant disease detection using ImageNET50

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebook#fileId=https%3A//storage.googleapis.com/kaggle-colab-exported-notebooks/noormohmed/plant-disease-detection-using-imagenet50.9d9a8dc4-9991-483d-b02a-5c2240b0890b.ipynb%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com/20260912/auto/storage/goog4_request%26X-Goog-Date%3D20260912T165434Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3D02ad225e8c61f248987a9bd7f4f06fc1089b5a29c3496e6ecdf8ed90f05e66893da3c8b702a9e8a31d79c060e9c195dd5421d06b3cfb3b347108e455d9cffa0d516a6f83f653f21fa82e164e55c25a66219d6af1c3ad110b5b2fe02ddeefedcfdd1ab749545f90c3e494c2b77a71619fb1aed7627c72944aef1c6ed7a31921453b3167ed0efd49cdec9e11eb3973c2e0c66aaeb305469e85e9c3bca806f5fdca41e0ebb1bc7bcacf99e8a272164749ef2da47081b5c10e9104523d30d2abc6b415e9596ba944c9cd0bf0458240b6f1b231c8b5e5e2ad0f9794568e03f3a776c8d0379af86757012f05518f0452c912e365e9ece870e76a9b4d5fbe0ae343fa61
"""

# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES,
# THEN FEEL FREE TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON
# ENVIRONMENT SO THERE MAY BE MISSING LIBRARIES USED BY YOUR
# NOTEBOOK.
import kagglehub
emmarex_plantdisease_path = kagglehub.dataset_download('emmarex/plantdisease')

print('Data source import complete.')

import kagglehub
import os

# Download latest version
path = kagglehub.dataset_download("emmarex/plantdisease")

print("Path to dataset files:", path)

dataset_path='/kaggle/input/datasets/emmarex/plantdisease'

"""**IMPORTANT CHECKS FOR DATA**"""

import os

dataset_path = '/kaggle/input/datasets/emmarex/plantdisease'

for root, dirs, files in os.walk(dataset_path):
    level = root.replace(dataset_path, '').count(os.sep)
    indent = '    ' * level

    print(f"{indent}{os.path.basename(root)}/")

    if level < 2:
        for file in files[:5]:
            print(f"{indent}    {file}")

"""**TO check if the dataset is duplicated**"""

import os

path1 = '/kaggle/input/datasets/emmarex/plantdisease/PlantVillage'
path2 = '/kaggle/input/datasets/emmarex/plantdisease/plantvillage/PlantVillage'

def get_counts(path):
    counts = {}

    for cls in os.listdir(path):
        class_path = os.path.join(path, cls)

        if os.path.isdir(class_path):
            counts[cls] = len([
                f for f in os.listdir(class_path)
                if f.lower().endswith(('.jpg', '.jpeg', '.png'))
            ])

    return counts

counts1 = get_counts(path1)
counts2 = get_counts(path2)

print("Version 1:")
print("Classes:", len(counts1))
print("Images:", sum(counts1.values()))

print("\nVersion 2:")
print("Classes:", len(counts2))
print("Images:", sum(counts2.values()))
import os
import hashlib

def get_hashes(path):
    hashes = set()

    for cls in os.listdir(path):
        class_path = os.path.join(path, cls)

        if os.path.isdir(class_path):
            for file in os.listdir(class_path):
                if file.lower().endswith(('.jpg', '.jpeg', '.png')):
                    file_path = os.path.join(class_path, file)

                    with open(file_path, 'rb') as f:
                        file_hash = hashlib.md5(f.read()).hexdigest()

                    hashes.add(file_hash)

    return hashes

hashes1 = get_hashes(path1)
hashes2 = get_hashes(path2)

print("Images in version 1:", len(hashes1))
print("Images in version 2:", len(hashes2))

print("Same images:", hashes1 == hashes2)

print("Common images:", len(hashes1.intersection(hashes2)))

print("\nClass distribution:")
for cls in sorted(counts1):
    print(f"{cls}: {counts1[cls]}")

dataset_path = '/kaggle/input/datasets/emmarex/plantdisease/PlantVillage'

import os
from collections import Counter

class_counts = {}

for cls in os.listdir(dataset_path):
    class_path = os.path.join(dataset_path, cls)

    if os.path.isdir(class_path):
        count = len([
            f for f in os.listdir(class_path)
            if f.lower().endswith(('.jpg', '.jpeg', '.png'))
        ])
        class_counts[cls] = count

for cls, count in sorted(class_counts.items()):
    print(f"{cls}: {count}")

print("\nTotal:", sum(class_counts.values()))

import os
import shutil
from sklearn.model_selection import train_test_split

# Original dataset
dataset_path = '/kaggle/input/datasets/emmarex/plantdisease/PlantVillage'

# Output directory
split_path = '/kaggle/working/PlantVillage_split'

# Create folders
for split in ['train', 'val', 'test']:
    os.makedirs(os.path.join(split_path, split), exist_ok=True)

# Get classes
classes = [
    cls for cls in os.listdir(dataset_path)
    if os.path.isdir(os.path.join(dataset_path, cls))
]

print("Number of classes:", len(classes))

# Split each class separately
for cls in sorted(classes):

    class_path = os.path.join(dataset_path, cls)

    images = [
        f for f in os.listdir(class_path)
        if f.lower().endswith(('.jpg', '.jpeg', '.png'))
    ]

    # 80% train, 20% temporary
    train_images, temp_images = train_test_split(
        images,
        test_size=0.20,
        random_state=42
    )

    # 10% validation, 10% test
    val_images, test_images = train_test_split(
        temp_images,
        test_size=0.50,
        random_state=42
    )

    # Create class directories
    for split in ['train', 'val', 'test']:
        os.makedirs(
            os.path.join(split_path, split, cls),
            exist_ok=True
        )

    # Copy files
    for image in train_images:
        shutil.copy2(
            os.path.join(class_path, image),
            os.path.join(split_path, 'train', cls, image)
        )

    for image in val_images:
        shutil.copy2(
            os.path.join(class_path, image),
            os.path.join(split_path, 'val', cls, image)
        )

    for image in test_images:
        shutil.copy2(
            os.path.join(class_path, image),
            os.path.join(split_path, 'test', cls, image)
        )

    print(
        f"{cls}: "
        f"Train={len(train_images)}, "
        f"Val={len(val_images)}, "
        f"Test={len(test_images)}"
    )

from tensorflow.keras.preprocessing.image import ImageDataGenerator, load_img, img_to_array

train_path = os.path.join(split_path, 'train')
target_count = 1000

minority_classes = [
    'Potato___healthy',
    'Tomato__Tomato_mosaic_virus',
    'Tomato_Leaf_Mold',
    'Pepper__bell___Bacterial_spot'
]

datagen = ImageDataGenerator(
    rotation_range=20,
    width_shift_range=0.10,
    height_shift_range=0.10,
    shear_range=0.10,
    zoom_range=0.15,
    horizontal_flip=True,
    brightness_range=[0.8, 1.2],
    fill_mode='nearest'
)

import numpy as np
for class_name in minority_classes:

    class_path = os.path.join(train_path, class_name)

    # Get original images
    image_files = [
        f for f in os.listdir(class_path)
        if f.lower().endswith(('.jpg', '.jpeg', '.png'))
    ]

    current_count = len(image_files)
    needed = target_count - current_count

    print(f'\n{class_name}')
    print(f'Current: {current_count}')
    print(f'Need: {max(0, needed)}')

    if needed <= 0:
        continue

    generated = 0

    while generated < needed:

        # Randomly select an original image
        image_file = np.random.choice(image_files)
        image_path = os.path.join(class_path, image_file)

        # Load image
        img = load_img(image_path)
        x = img_to_array(img)
        x = np.expand_dims(x, axis=0)

        # Generate one augmented image
        generator = datagen.flow(
            x,
            batch_size=1,
            save_to_dir=class_path,
            save_prefix='aug',
            save_format='jpg'
        )

        next(generator)

        generated += 1

    print(f'Generated: {generated}')

for class_name in sorted(os.listdir(train_path)):

    class_path = os.path.join(train_path, class_name)

    if os.path.isdir(class_path):

        count = len([
            f for f in os.listdir(class_path)
            if f.lower().endswith(('.jpg', '.jpeg', '.png'))
        ])

        print(f'{class_name}: {count}')

import tensorflow as tf
import os

train_path = '/kaggle/working/PlantVillage_split/train'
val_path   = '/kaggle/working/PlantVillage_split/val'
test_path  = '/kaggle/working/PlantVillage_split/test'

IMG_SIZE = (224, 224)
BATCH_SIZE = 32
SEED = 42

train_ds = tf.keras.utils.image_dataset_from_directory(
    train_path,
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    shuffle=True,
    seed=SEED
)

val_ds = tf.keras.utils.image_dataset_from_directory(
    val_path,
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    shuffle=False
)

test_ds = tf.keras.utils.image_dataset_from_directory(
    test_path,
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    shuffle=False
)

class_names = train_ds.class_names

print("Number of classes:", len(class_names))
print("Classes:")

for i, name in enumerate(class_names):
    print(i, ":", name)

AUTOTUNE = tf.data.AUTOTUNE

train_ds = train_ds.prefetch(AUTOTUNE)
val_ds = val_ds.prefetch(AUTOTUNE)
test_ds = test_ds.prefetch(AUTOTUNE)

AUTOTUNE = tf.data.AUTOTUNE

train_ds = train_ds.prefetch(AUTOTUNE)
val_ds = val_ds.prefetch(AUTOTUNE)
test_ds = test_ds.prefetch(AUTOTUNE)

data_augmentation = tf.keras.Sequential([
    tf.keras.layers.RandomFlip("horizontal"),
    tf.keras.layers.RandomRotation(0.08),
    tf.keras.layers.RandomZoom(0.10),
    tf.keras.layers.RandomContrast(0.10),
], name="data_augmentation")

from tensorflow.keras.applications import EfficientNetB0
from tensorflow.keras import layers, models

num_classes = len(class_names)

base_model = EfficientNetB0(
    include_top=False,
    weights='imagenet',
    input_shape=(224, 224, 3)
)

base_model.trainable = False

inputs = layers.Input(shape=(224, 224, 3))

x = data_augmentation(inputs)

x = base_model(x, training=False)

x = layers.GlobalAveragePooling2D()(x)

x = layers.Dropout(0.3)(x)

outputs = layers.Dense(
    num_classes,
    activation='softmax'
)(x)

model = models.Model(inputs, outputs)

model.compile(
    optimizer=tf.keras.optimizers.Adam(
        learning_rate=1e-3
    ),
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

model.compile(
    optimizer=tf.keras.optimizers.Adam(
        learning_rate=1e-3
    ),
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

callbacks = [
    tf.keras.callbacks.EarlyStopping(
        monitor='val_loss',
        patience=5,
        restore_best_weights=True
    ),

    tf.keras.callbacks.ReduceLROnPlateau(
        monitor='val_loss',
        factor=0.2,
        patience=2,
        min_lr=1e-7
    ),

    tf.keras.callbacks.ModelCheckpoint(
        '/kaggle/working/best_efficientnetb0.keras',
        monitor='val_accuracy',
        save_best_only=True
    )
]

history = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=15,
    callbacks=callbacks
)

from sklearn.metrics import classification_report, confusion_matrix
import numpy as np

# Get true labels
y_true = np.concatenate([
    y.numpy() for x, y in val_ds
])

# Predict
y_pred_probs = model.predict(val_ds)
y_pred = np.argmax(y_pred_probs, axis=1)

print(classification_report(
    y_true,
    y_pred,
    target_names=class_names,
    digits=4
))

"""**Fine Tunnig**"""

base_model.trainable = True

for layer in base_model.layers[:-30]:
    layer.trainable = False

# Make sure BatchNorm layers remain frozen
for layer in base_model.layers:
    if isinstance(layer, tf.keras.layers.BatchNormalization):
        layer.trainable = False

trainable_count = sum(
    layer.trainable for layer in model.layers
)

print("Trainable layers:", trainable_count)

model.compile(
    optimizer=tf.keras.optimizers.Adam(
        learning_rate=1e-5
    ),
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

fine_tune_callbacks = [
    tf.keras.callbacks.EarlyStopping(
        monitor='val_loss',
        patience=5,
        restore_best_weights=True
    ),

    tf.keras.callbacks.ReduceLROnPlateau(
        monitor='val_loss',
        factor=0.2,
        patience=2,
        min_lr=1e-7
    ),

    tf.keras.callbacks.ModelCheckpoint(
        '/kaggle/working/best_efficientnetb0_finetuned.keras',
        monitor='val_accuracy',
        save_best_only=True
    )
]

fine_tune_history = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=15,
    callbacks=fine_tune_callbacks
)

from sklearn.metrics import classification_report
import numpy as np

y_true = np.concatenate([
    y.numpy() for x, y in val_ds
])

y_pred_probs = model.predict(val_ds)
y_pred = np.argmax(y_pred_probs, axis=1)

print(classification_report(
    y_true,
    y_pred,
    target_names=class_names,
    digits=4
))

test_loss, test_accuracy = model.evaluate(test_ds)

print("Test Loss:", test_loss)
print("Test Accuracy:", test_accuracy)